name: Detekt Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # or your project's Java version

      - name: Run Detekt
        run: ./gradlew detekt